Repository chihacknight/ghost-buses-frontend, pull requests merged in 2023-08, with the labels that each got.

#95 Change scss to condense the header
  src/scss/_header-animation.scss
  src/scss/_header.scss
  src/scss/_socials.scss
Labels: bug, enhancement, Needs Review

#84 Update route highlight to bring highlighted route to top
  src/components/Map.js
Labels: enhancement, Needs Review

#105 fix: add aria-label to <a> elements
  src/Pages/InteractiveMap.js
  src/components/Socials.js
Labels: Accessibility
